### ISSUE TITLE
Support all DynamoDB service endpoints

### ISSUE THREAD

**Issue by mrbelk** [kcargile/log4net.dynamodb#2]
Currently, this appender only supports the default service endpoint of http://dynamodb.us-east-1.amazonaws.com.  This renders the appender not very useful for people in other regions like us-west-1 or us-west-2.

**Comment by mrbelk** [comment]
I'm not familiar enough with git to issue a pull request, but the gist of the change I made is to add a new string property to the DynamoDbAppender class called "ServiceUrl" and add a const DefaultServiceUrl string of "http://dynamodb.us-east-1.amazonaws.com" that populates the instance property in the constructor.  Then, when the DynamoDbClient object is created, it uses the constructor overload that takes a DynamoDbConfig object with the ServiceURL property set to the appender's ServiceUrl property.

**Comment by mrbelk** [comment]
Here is a link to a gist with my proposed changes: https://gist.github.com/mrbelk/5316122

**Comment by kcargile** [comment]
Thanks for pointing this out and for the gist. I'll roll this in with some other changes I'm making today.

**Comment by mrbelk** [comment]
You're welcome.  I was pulling my hair out last night trying to figure out why I kept getting HTTP 400 errors that the resource wasn't found.

**Comment by kcargile** [comment]
I just committed changes that address this issue. I have also been making some other major changes to the appender, namely parameterizing the schema via configuration. Take a look and please let me know if you run into any more issues. Thanks again for the help.

Updated package for 2.1.0 is also on Nuget.

**Comment by mrbelk** [comment]
Are all of the "<parameter />" specifiers explicitly required?

**Comment by mrbelk** [comment]
Thanks. Are the parameter elements required?  How would I get exception message or stack trace data into the log record?

-M

mobile MrB 4.0

On Apr 5, 2013, at 8:05 PM, "Kristopher Cargile" <notifications@github.com<mailto:notifications@github.com>> wrote:

I just committed changes that address this issue. I have also been making some other major changes to the appender, namely parameterizing the schema via configuration. Take a look and please let me know if you run into any more issues. Thanks again for the help.

Updated package for 2.1.0 is also on Nuget.

**Comment by kcargile** [comment]
Yes, you'll need to define the parameters that you want to capture.

You can use the standard log4net tokens (e.g. %exception, %message, %stacktrace{level}, etc.) and/or your own tokens to define what data you want to capture. Have a look at the project readme or the unit test project for an example of how both of these scenarios work.

The log4net tokens are all pretty well documented on the log4net site [here](http://logging.apache.org/log4net/release/sdk/log4net.Layout.PatternLayout.html).

Note that when you use a B data type parameter, the object will be serialized and saved to the database. Using an S type will call the ToString() method on the object you're persisting before the DynamoDb attribute value is set, so the result here vary based on concrete type and its specific implementation of ToString().

HTH
-k
